import pluginJs from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'

const maxStatements = 12

export default [
  { files: ['**/*.{js,mjs,cjs,ts}'] },
  { ignores: ['**/.yarn/**', '**/dist/**'] },
  { languageOptions: { globals: globals.node } },
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      'array-callback-return': 2,
      'no-await-in-loop': 2,
      'no-constructor-return': 2,
      // 'no-duplicate-imports': 2,
      'no-inner-declarations': 2,
      'no-promise-executor-return': 2,
      'no-self-compare': 2,
      'no-template-curly-in-string': 2,
      'no-unmodified-loop-condition': 2,
      'no-unreachable-loop': 2,
      'no-use-before-define': 'off',
      '@typescript-eslint/no-use-before-define': [
        'error',
        {
          functions: false,
          classes: true,
          variables: true,
          allowNamedExports: false,
          typedefs: false,
        },
      ],

      'no-useless-assignment': 2,
      'require-atomic-updates': 2,
      'accessor-pairs': 2,
      'arrow-body-style': 2,
      'block-scoped-var': 2,
      camelcase: 2,
      'capitalized-comments': 'off',
      'class-methods-use-this': 2,
      complexity: 2,
      'consistent-return': 2,
      'consistent-this': 2,
      curly: 2,
      'default-case': 2,
      'default-case-last': 2,
      'default-param-last': 2,
      'dot-notation': 2,
      eqeqeq: 2,
      'func-name-matching': 2,
      'func-names': 2,
      'func-style': 0,
      'grouped-accessor-pairs': 2,
      'guard-for-in': 2,
      'id-denylist': 2,
      'id-length': ['error', { exceptions: ['i', 'r', 'v', 'b', 'x', 'y', 'z'] }],
      'id-match': 2,
      'init-declarations': 2,
      'logical-assignment-operators': 2,
      'max-classes-per-file': 2,
      'max-depth': 2,
      'max-lines': 2,
      'max-lines-per-function': 2,
      'max-nested-callbacks': 2,
      'max-params': 2,
      'max-statements': ['error', maxStatements, { ignoreTopLevelFunctions: true }],
      'new-cap': 2,
      'no-alert': 2,
      'no-array-constructor': 2,
      'no-bitwise': 2,
      'no-caller': 2,
      'no-console': 'off',
      'no-continue': 2,
      'no-div-regex': 2,
      'no-else-return': 2,
      'no-empty-function': 2,
      'no-eq-null': 2,
      'no-eval': 2,
      'no-extend-native': 2,
      'no-extra-bind': 2,
      'no-extra-label': 2,
      'no-implicit-coercion': 2,
      'no-implicit-globals': 2,
      'no-implied-eval': 2,
      'no-inline-comments': 'off',
      'no-invalid-this': 2,
      'no-iterator': 2,
      'no-label-var': 2,
      'no-labels': 2,
      'no-lone-blocks': 2,
      'no-lonely-if': 2,
      'no-loop-func': 2,
      'no-magic-numbers': ['error', { ignore: [0, 1, 2], ignoreDefaultValues: true }],
      'no-multi-assign': 2,
      'no-multi-str': 2,
      'no-negated-condition': 2,
      'no-nested-ternary': 2,
      'no-new': 2,
      'no-new-func': 2,
      'no-new-wrappers': 2,
      'no-object-constructor': 2,
      'no-octal-escape': 2,
      'no-param-reassign': 2,
      'no-plusplus': 2,
      'no-proto': 2,
      'no-restricted-exports': 2,
      'no-restricted-globals': 2,
      'no-restricted-imports': 2,
      'no-restricted-properties': 2,
      'no-restricted-syntax': 2,
      'no-return-assign': 2,
      'no-script-url': 2,
      'no-sequences': 2,
      'no-shadow': 2,
      'no-ternary': 'off',
      'no-throw-literal': 2,
      'no-undef-init': 2,
      'no-undefined': 2,
      'no-underscore-dangle': 2,
      'no-unneeded-ternary': 2,
      'no-unused-expressions': 'off',
      '@typescript-eslint/no-unused-expressions': [
        'error',
        { allowShortCircuit: true, allowTernary: true },
      ],
      'no-useless-call': 2,
      'no-useless-computed-key': 2,
      'no-useless-concat': 2,
      'no-useless-constructor': 2,
      'no-useless-rename': 2,
      'no-useless-return': 2,
      'no-var': 2,
      'no-void': 2,
      'no-warning-comments': 'off',
      'object-shorthand': 2,
      // 'one-var': 2,
      'operator-assignment': 2,
      'prefer-arrow-callback': 2,
      'prefer-const': 2,
      'prefer-destructuring': 2,
      'prefer-exponentiation-operator': 2,
      'prefer-named-capture-group': 2,
      'prefer-numeric-literals': 2,
      'prefer-object-has-own': 'off', // ES2022
      'prefer-object-spread': 2,
      'prefer-promise-reject-errors': 2,
      'prefer-regex-literals': 2,
      'prefer-rest-params': 2,
      'prefer-spread': 2,
      'prefer-template': 2,
      radix: 2,
      'require-await': 2,
      'require-unicode-regexp': 2,
      // 'sort-imports': 2,
      // 'sort-keys': 2,
      'sort-vars': 2,
      strict: 2,
      'symbol-description': 2,
      'vars-on-top': 2,
      yoda: 2,
    },
  },
]
